<?php

/**
 * @file
 * Install and uninstall functions for the Anonymous session node access.
 */

/**
 * Implements hook_install().
 *
 * Creates default settings upon installation.
 */
function anonymous_session_nodeaccess_install() {
  db_insert('anonymous_session_nodeaccess')
    ->fields(array(
      'id' => 0,
      'content_types' => '',
      'permissions' => '',
      'published' => 0,
    ))
    ->execute();
}

/**
 * Implements hook_schema().
 */
function anonymous_session_nodeaccess_schema() {
  $schema['anonymous_session_nodeaccess'] = array(
    'description' => 'Settings for Anonymous session node access module.',
    'fields' => array(
      'id' => array(
        'description' => 'The primary identifier.',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'content_types' => array(
        'description' => 'Serialized string holding the content types set.',
        'type' => 'blob',
        'size' => 'normal',
        'serialize' => FALSE,
        'not null' => TRUE,
      ),
      'permissions' => array(
        'description' => 'Serialized string holding the permission types set.',
        'type' => 'blob',
        'size' => 'normal',
        'serialize' => FALSE,
        'not null' => TRUE,
      ),
      'published' => array(
        'description' => 'Boolean holding the value of published.',
        'type' => 'int',
        'size' => 'tiny',
        'not null' => TRUE,
        'default' => 0,
      ),
    ),
    'primary key' => array(
      'id',
    ),
  );
  return $schema;
}
