<?php

/**
 * @file
 * Install and uninstall functions for the Session node access.
 */

/**
 * Implements hook_install().
 *
 * Creates default settings upon installation.
 */
function session_node_access_install() {
  db_insert('session_node_access')
    ->fields(array(
      'id' => 0,
      'content_types' => '',
      'user_roles' => '',
      'permissions' => '',
      'published' => 0,
    ))
    ->execute();
}

/**
 * Implements hook_schema().
 */
function session_node_access_schema() {
  $schema['session_node_access'] = array(
    'description' => 'Settings for Session node access module.',
    'fields' => array(
      'id' => array(
        'description' => 'The primary identifier.',
        'type' => 'int',
        'unsigned' => TRUE,
        'not null' => TRUE,
      ),
      'content_types' => array(
        'description' => 'Serialized string holding the content types set.',
        'type' => 'blob',
        'size' => 'normal',
        'serialize' => FALSE,
        'not null' => TRUE,
      ),
      'user_roles' => array(
        'description' => 'Serialized string holding the user types set.',
        'type' => 'blob',
        'size' => 'normal',
        'serialize' => FALSE,
        'not null' => TRUE,
      ),
      'permissions' => array(
        'description' => 'Serialized string holding the permission types set.',
        'type' => 'blob',
        'size' => 'normal',
        'serialize' => FALSE,
        'not null' => TRUE,
      ),
      'published' => array(
        'description' => 'Boolean holding the value of published.',
        'type' => 'int',
        'size' => 'tiny',
        'not null' => TRUE,
        'default' => 0,
      ),
    ),
    'primary key' => array(
      'id',
    ),
  );
  return $schema;
}
