<?php

/**
 * Implements hook_help().
 */
function session_node_access_help($route_name, RouteMatchInterface $route_match) {
  return $route_name === 'help.page.session_node_access' ?
    check_markup(file_get_contents(dirname(__FILE__) . "/README.md")) : NULL;
}

/**
 * Implements hook_node_access().
 *
 * Grants access to users to view/edit/delete a node (depending
 * on settings) in case they created it in their current session.
 */
function session_node_access_node_access(\Drupal\node\NodeInterface $node, $op, \Drupal\Core\Session\AccountInterface $account) {
  if (session_node_access_user_node_access($node, $op, $account)) {

    // Grant access for this user to this node user.
    return \Drupal\Core\Access\AccessResult::allowed();
  }
  return \Drupal\Core\Access\AccessResult::neutral();
}


/**
 * Implements hook_entity_insert().
 *
 * Makes sure that content created by users gets referenced in their
 * session variable to be checked for in hook_node_access.
 */
function session_node_access_entity_insert(Drupal\Core\Entity\EntityInterface $node) {
  if ($node->getEntityType()->id() != 'node') {
    return;
  }
  $config = \Drupal::config('session_node_access.settings');

  if (isset($config->get('node_types')[$node->getType()]) && $config->get('node_types')[$node->getType()]) {
    $account = \Drupal::currentUser();
    if (is_array($config->get('user_roles'))) {
      foreach ($account->getRoles() as $role_id) {
        if (isset($config->get('user_roles')[$role_id]) && $config->get('user_roles')[$role_id]) {
          $_SESSION['session_node_access']['nodes_created'][] = $node->id();
          break;
        }
      }
    }
  }
}

/**
 * Checks if currently logged in user has access to a node.
 *
 * @param \Drupal\node\NodeInterface $node
 *   The node to be checked if accessible by currently logged in user.
 * @param string $op
 *   The user operation for which to check access (view/update/delete).
 * @param \Drupal\Core\Session\AccountInterface $account
 *   The user to be checked for access to the node.
 *   If not provided, current user is taken.
 *
 * @return bool
 *   True if user has access, false if they do not.
 */
function session_node_access_user_node_access(\Drupal\node\NodeInterface $node, $op, \Drupal\Core\Session\AccountInterface $account) {
  if (!isset($_SESSION['session_node_access']['nodes_created'])) {
    return FALSE;
  }

  $config = \Drupal::config('session_node_access.settings');

  // Check if settings allow granting permissions to this node.
  if (isset($config->get('operations')[$op]) && $config->get('operations')[$op]) {
    if (isset($config->get('node_types')[$node->getType()]) && $config->get('node_types')[$node->getType()]) {
      if (is_array($config->get('user_roles'))) {
        foreach ($account->getRoles() as $role_id) {
          if (isset($config->get('user_roles')[$role_id]) && $config->get('user_roles')[$role_id]) {
            if (!$config->get('published') || $node->isPublished()) {
              if (in_array($node->id(), $_SESSION['session_node_access']['nodes_created'])) {
                return TRUE;
              }
            }
          }
        }
      }
    }
  }
  return FALSE;
}
